name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shelfshare-front-end:latest
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PASSWORD }}
          script: |
            sudo docker login
            sudo docker pull cjedgecombe/shelfshare-front-end:latest
            sudo docker container stop shelfshareFE
            sudo docker container rm shelfshareFE
            sudo docker run -d --name shelfshareFE -e PORT=3000 -e API_URL=${{ secrects.API_URL }} -p 80:3000 cjedgecombe/shelfshare-front-end:latest
            sudo docker image prune -f
